# Generated by Django 6.0.7 on 2026-09-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the selling price in Indian rupees.', max_digits=10, verbose_name='Price (INR)'),
        ),
    ]
